/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NegativeRouteImport } from './routes/negative'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as CyberbullyingRouteImport } from './routes/cyberbullying'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as BlacklistRouteImport } from './routes/blacklist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncPlatformsRouteImport } from './routes/api/public/hooks/sync-platforms'
import { Route as ApiPublicHooksProcessJobsRouteImport } from './routes/api/public/hooks/process-jobs'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NegativeRoute = NegativeRouteImport.update({
  id: '/negative',
  path: '/negative',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberbullyingRoute = CyberbullyingRouteImport.update({
  id: '/cyberbullying',
  path: '/cyberbullying',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlacklistRoute = BlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncPlatformsRoute =
  ApiPublicHooksSyncPlatformsRouteImport.update({
    id: '/api/public/hooks/sync-platforms',
    path: '/api/public/hooks/sync-platforms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessJobsRoute =
  ApiPublicHooksProcessJobsRouteImport.update({
    id: '/api/public/hooks/process-jobs',
    path: '/api/public/hooks/process-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/comments': typeof CommentsRoute
  '/cyberbullying': typeof CyberbullyingRoute
  '/moderation': typeof ModerationRoute
  '/negative': typeof NegativeRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translator': typeof TranslatorRoute
  '/workflows': typeof WorkflowsRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/api/public/hooks/sync-platforms': typeof ApiPublicHooksSyncPlatformsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/comments': typeof CommentsRoute
  '/cyberbullying': typeof CyberbullyingRoute
  '/moderation': typeof ModerationRoute
  '/negative': typeof NegativeRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translator': typeof TranslatorRoute
  '/workflows': typeof WorkflowsRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/api/public/hooks/sync-platforms': typeof ApiPublicHooksSyncPlatformsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/comments': typeof CommentsRoute
  '/cyberbullying': typeof CyberbullyingRoute
  '/moderation': typeof ModerationRoute
  '/negative': typeof NegativeRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/translator': typeof TranslatorRoute
  '/workflows': typeof WorkflowsRoute
  '/api/public/hooks/process-jobs': typeof ApiPublicHooksProcessJobsRoute
  '/api/public/hooks/sync-platforms': typeof ApiPublicHooksSyncPlatformsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blacklist'
    | '/comments'
    | '/cyberbullying'
    | '/moderation'
    | '/negative'
    | '/reports'
    | '/research'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/translator'
    | '/workflows'
    | '/api/public/hooks/process-jobs'
    | '/api/public/hooks/sync-platforms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/blacklist'
    | '/comments'
    | '/cyberbullying'
    | '/moderation'
    | '/negative'
    | '/reports'
    | '/research'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/translator'
    | '/workflows'
    | '/api/public/hooks/process-jobs'
    | '/api/public/hooks/sync-platforms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blacklist'
    | '/comments'
    | '/cyberbullying'
    | '/moderation'
    | '/negative'
    | '/reports'
    | '/research'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/translator'
    | '/workflows'
    | '/api/public/hooks/process-jobs'
    | '/api/public/hooks/sync-platforms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlacklistRoute: typeof BlacklistRoute
  CommentsRoute: typeof CommentsRoute
  CyberbullyingRoute: typeof CyberbullyingRoute
  ModerationRoute: typeof ModerationRoute
  NegativeRoute: typeof NegativeRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TranslatorRoute: typeof TranslatorRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiPublicHooksProcessJobsRoute: typeof ApiPublicHooksProcessJobsRoute
  ApiPublicHooksSyncPlatformsRoute: typeof ApiPublicHooksSyncPlatformsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negative': {
      id: '/negative'
      path: '/negative'
      fullPath: '/negative'
      preLoaderRoute: typeof NegativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberbullying': {
      id: '/cyberbullying'
      path: '/cyberbullying'
      fullPath: '/cyberbullying'
      preLoaderRoute: typeof CyberbullyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blacklist': {
      id: '/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof BlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-platforms': {
      id: '/api/public/hooks/sync-platforms'
      path: '/api/public/hooks/sync-platforms'
      fullPath: '/api/public/hooks/sync-platforms'
      preLoaderRoute: typeof ApiPublicHooksSyncPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-jobs': {
      id: '/api/public/hooks/process-jobs'
      path: '/api/public/hooks/process-jobs'
      fullPath: '/api/public/hooks/process-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlacklistRoute: BlacklistRoute,
  CommentsRoute: CommentsRoute,
  CyberbullyingRoute: CyberbullyingRoute,
  ModerationRoute: ModerationRoute,
  NegativeRoute: NegativeRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TranslatorRoute: TranslatorRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiPublicHooksProcessJobsRoute: ApiPublicHooksProcessJobsRoute,
  ApiPublicHooksSyncPlatformsRoute: ApiPublicHooksSyncPlatformsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
